### PR TITLE
[WIP] RavenDB 3.0 support / NServiceBus.RavenDB version 3.0

### PR DESCRIPTION
**Pull request by synhershko**

### CODE REVIEW

**Comment by synhershko** [comment]
This is now ready to be reviewed, while @danielmarbach and me verify the acceptance tests runs

/cc @andreasohlund @johnsimons @SimonCropp

**Comment by andreasohlund** [comment]
What's the status on this one?

**Comment by synhershko** [comment]
It's ready to be merged, first we want to release a stable version with outbox support, will happen in the next few days @danielmarbach

**Comment by andreasohlund** [comment]
Awesome

On Thu, Apr 2, 2015 at 9:10 AM, Itamar Syn-Hershko <notifications@github.com

**Comment by ramonsmits** [comment]
Will this become a new package `NServiceBus.RavenDBv3` instead of a new version of NServiceBus.RavenDB as mentioned by @johnsimons in #34 ?

**Comment by danielmarbach** [comment]
@ramonsmits Now it is ready to be merged. What @synhershko [said](https://github.com/Particular/NServiceBus.RavenDB/pull/61#issuecomment-88783493) still is true. I also moved develop to latest build templates. Need to merge that into the outbox as well

**Pull request merged**
