### PR TITLE
[wip] test unicode chars

### PR DESCRIPTION
**Pull request by weralabaj**
Particular/PlatformDevelopment#1256

### CODE REVIEW

**Comment by mauroservienti** [comment]
uhm, this is actually failing due to this:

```
System.Exception : To use the Outbox feature with MSMQ or SQLServer transports it must be enabled in the config file.
To do that add the following:
<appSettings>
    <add key="NServiceBus/Outbox" value="true"/>
</appSettings>
```

when setting up the endpoint the following needs to be set:

```
b.GetSettings().Set("DisableOutboxTransportCheck", true);
```

**Comment by weralabaj** [comment]
@mauroservienti I'll update when Tim approves my test in core :)

**Comment by mauroservienti** [comment]
cool. No worries.

**Comment by weralabaj** [comment]
This PR is just to verify if the test will pass immediately, but it'll be incorporated as part of AcceptanceTest suite so no need to merge. Still @mauroservienti if you could review if this test makes sense, that will be appreciated and then we can close this PR.

**Comment by weralabaj** [comment]
awesome tests pass, so I think we can close this :D

**Comment by mauroservienti** [comment]
thanks @weralabaj, closing.

**Pull request closed without merging**
