### PR TITLE
Stop using property injection

### PR DESCRIPTION
**Pull request by andreasohlund**
Paves the way for https://github.com/Particular/NServiceBus/pull/3467

### CODE REVIEW

**Comment by andreasohlund** [comment]
@Particular/transport-maintainers please review

**Comment by tmasternak** [comment]
@andreasohlund: This should probably get reviewed by persistence maintainers right?

**Comment by andreasohlund** [comment]
doh!

@Particular/persistence-maintainers please review

**Comment by andreasohlund** [comment]
Note that this is failing the same tests as the ones that fails on develop so I'm hoping that it doesn't break anything.

**Comment by colin-higgins** [comment]
Rebased with latest develop. All tests should pass now. Will merge when tests are green.

**Comment by andreasohlund** [comment]
And they are green now :)

**Pull request merged**
