### PR TITLE
Port of fixes to vnext

### PR DESCRIPTION
**Pull request by johnsimons**
Connects to Particular/PlatformDevelopment#697

Fix varying DocumentId naming strategies between provided vs generated DocumentStore

Centralizing DocumentStore management

### CODE REVIEW

**Comment by johnsimons** [comment]
@DavidBoike please review, this should bring all the changes that are about to going out into develop branch

**Comment by DavidBoike** [comment]
Hung up on GitVersion issues, same as #197

**Comment by johnsimons** [comment]
@DavidBoike so is the porting ok?

**Comment by DavidBoike** [comment]
I have no idea until I can build and test it. Working on a patch for GitVersion currently.

**Comment by johnsimons** [comment]
@DavidBoike I tested it by modifying the ObsoleteEx ranges, so the build works 😉

**Comment by DavidBoike** [comment]
I believe you! :wink: But I want to verify the behavior with my repro.

**Comment by DavidBoike** [comment]
Making this WIP. Because EndpointVersion is not present in V4 this cannot succeed when trying to connect with ConnectionParameters or to the default localhost:8080 connection string. Added a failing acceptance test for it.

**Comment by johnsimons** [comment]
@DavidBoike could the "EndpointVersion is not present in V4" be handled in a different PR ? So in essence this PR is just about:
- Fix varying DocumentId naming strategies between provided vs generated DocumentStore
- Centralizing DocumentStore management

**Comment by DavidBoike** [comment]
If we did a stopgap resource manager id based only on local address, yes.

**Pull request merged**
