### PR TITLE
Duplicate Subscriptions fix

### PR DESCRIPTION
**Pull request by weralabaj**
Resolves https://github.com/Particular/NServiceBus.RavenDB/issues/281

### CODE REVIEW

**Comment by weralabaj** [comment]
@Particular/ravendb-persistence-maintainers please review

**Comment by weralabaj** [comment]
That seems to be very closely related to https://github.com/Particular/NServiceBus.RavenDB/issues/280#issuecomment-249547566, seems it'd be best to address both at once.

**Comment by weralabaj** [comment]
I have a feeling I'm doing something silly with that test and implementaiton, but probably too tired now to catch it.

**Comment by weralabaj** [comment]
@mauroservienti suggested the issue might be overriding Equals, so that Raven doesn't detect changes in the document. I tried reverting changes done to equals (instead .Contains() I then used query with condition), modifying .TransportAddress instead of .Endpoint, documentStore.DatabaseCommands.Patch, and ScriptedPatchRequest. 

None of them worked. Using `ScriptedPatchRequest` I was able to modify the MessageType for this document but not properties of Subscribers.

I'm running out of ideas.

**Comment by weralabaj** [comment]
I think that was the closest:

> documentStore.DatabaseCommands.Patch(
                                    subscriptionDocId,
                                    new[]
                                        {
                                        new PatchRequest
                                            {
                                                Type = PatchCommandType.Modify,
                                                Position = 0,
                                                Name = "Subscribers",
                                                Nested = new []
                                                             {
                                                                 new PatchRequest
                                                                     {
                                                                         Type = PatchCommandType.Set,
                                                                         Name = "Endpoint",
                                                                         Value = "Newtitle"
                                                                     }
                                                             }
                                            }
                                        });

Since I'm not sure about whether Position starts with 1 or 0, I tried both.

**Comment by weralabaj** [comment]
Scenarios to smoke test after upgrade:
- Side-by-side v5 and v6 endpoint publishers/subscribers (no-downtime deployment)
- Upgrade v5 to v6
- V5 and V6 subscribers at the same time

**Comment by weralabaj** [comment]
@Particular/ravendb-persistence-maintainers please review now, I think this is the last thing before RTM, correct?

**Comment by DavidBoike** [comment]
This PR should fix both #280 and #281, correct?

**Comment by weralabaj** [comment]
@DavidBoike yes

**Pull request merged**
