### PR TITLE
[WIP][INVESTIGATION] Raven saga pointer doc StoreAsync concurrency

### PR DESCRIPTION
**Pull request by DavidBoike**
We've discovered a difference in how Raven's sync/async APIs behave for storing documents, specifically a pointer document for a saga correlation property.

* Synchronous Store(doc) will not overwrite a previously existing document
* StoreAsync(doc) will *happily* overwrite a previously existing document, doing no sort of concurrency check unless you provide an `Etag` instance to compare against. If you are assuming you are creating a new document, you need to provide `Etag.Empty` for that check to take place.

This is a necessary fix, but more was required to fix this acceptance test (which is from core).

* Test is a saga that is supposed to process 2 messages in the same saga.
* 2nd message is sent in response to the first
* 2nd message starts to execute and queries Raven before pointer doc is committed/available
* 2nd message attempts to store pointer doc
  * Used to overwrite, leading to incorrect results
  * Now throws concurrency exception, leading to retry
* Added FLR features and other stuff so retries could actually happen
* Because in-memory test context object does not roll back with transaction, had to move the "test done" to a second message/handler

### BUT WAIT

If the Raven transaction and the MSMQ transaction are supposed to commit together, why is the OUTGOING message from the first handler happening BEFORE the Raven data is available to be loaded?

To me, this points to one of two possibiliites:

1. Because Raven commit is at the client-side, MSMQ is actually *faster* than Raven's ability to make the newly committed data available to load requests.
2. The SendLocalAsync is actually sending the message out prematurely.

I suspect the first option. How do we verify this either way?

ping: @Particular/tf-async-persistence

### CODE REVIEW

**Comment by colin-higgins** [comment]
I still don't understand why changing the message handler to this didn't afford Raven the time to finish committing everything: 
```C#
                public Task Handle(StartSagaMessage message, IMessageHandlerContext context)
                {
                    Data.SomeId = message.SomeId;

                    if (message.SecondMessage)
                    {
                        TestContext.SecondSagaId = Data.Id;
                        TestContext.SecondMessageReceived = true;
                    }
                    else
                    {
                        TestContext.FirstSagaId = Data.Id;
                        Task.Run(() =>
                        {
                            Task.Delay(5000);
                            context.SendLocal(new StartSagaMessage { SomeId = message.SomeId, SecondMessage = true });
                        });
                    }
                    return Task.FromResult(0);
                }
```

Also, in the saga persister we are using `Load`, not `Query`. Meaning if we have the document id, we should be able to get the non stale results after `SaveChanges` has been called. 

I think this has to be a failing in Raven's management of transactions. It is as if the changes are not actually being saved until we hit raven again and fail.

**Comment by johnsimons** [comment]
I have done a bit of digging around and definetly there is something off with Raven when it comes to async API

Here is the server output from running:

```
Request #  12: GET     -     0 ms - f4b29692-df2d-4051-b907-6e87b5f14d82 - 200 - http://localhost:8083/databases/f4b29692-df2d-4051-b907-6e87b5f14d82/queries/?include=SagaDocId&id=MoreThan127%2Fdac38a86-b3ae-dc7c-3b29-83e7c9694868%2Fab8a1ae2-c95a-4ae0-2650-020c3109ca08 Results count: 1, includes count: 0
Request #  13: POST    -     1 ms - f4b29692-df2d-4051-b907-6e87b5f14d82 - 200 - http://localhost:8083/databases/f4b29692-df2d-4051-b907-6e87b5f14d82/transaction/commit?tx=750caee0-6751-49e0-aae8-44005b36bc6f:7
Request #  14: POST    -     1 ms - f4b29692-df2d-4051-b907-6e87b5f14d82 - 500 - http://localhost:8083/databases/f4b29692-df2d-4051-b907-6e87b5f14d82/transaction/commit?tx=750caee0-6751-49e0-aae8-44005b36bc6f:7
Request #  15: POST    -     0 ms - f4b29692-df2d-4051-b907-6e87b5f14d82 - 200 - http://localhost:8083/databases/f4b29692-df2d-4051-b907-6e87b5f14d82/transaction/prepare?tx=750caee0-6751-49e0-aae8-44005b36bc6f:102&resourceManagerId=8f887ea4
-dedf-497d-85ce-245a12990672
Request #  16: POST    -     0 ms - f4b29692-df2d-4051-b907-6e87b5f14d82 - 200 - http://localhost:8083/databases/f4b29692-df2d-4051-b907-6e87b5f14d82/transaction/commit?tx=750caee0-6751-49e0-aae8-44005b36bc6f:102
```

So as u can see we have request 13, doing a commit, before the prepare is issued

If we look at the same test run against the synchronous version (vurrent production version):
```
Request #  10: POST    -     3 ms - 759e59c1-af04-4ba1-9dc7-66b960d9fe99 - 200 - http://localhost:8083/databases/759e59c1-af04-4ba1-9dc7-66b960d9fe99/transaction/prepare?tx=08464196-4f53-4e64-8738-6a060ca7acc5:1
Request #  11: POST    -     1 ms - 759e59c1-af04-4ba1-9dc7-66b960d9fe99 - 200 - http://localhost:8083/databases/759e59c1-af04-4ba1-9dc7-66b960d9fe99/transaction/commit?tx=08464196-4f53-4e64-8738-6a060ca7acc5:1
Request #  12: GET     -     2 ms - 759e59c1-af04-4ba1-9dc7-66b960d9fe99 - 200 - http://localhost:8083/databases/759e59c1-af04-4ba1-9dc7-66b960d9fe99/queries/?include=SagaDocId&id=MoreThan127%2F4f34a3a9-9c98-006c-05b8-081eebec5e5b%2Ffd95504
8-f55a-d4be-f193-82779b279a2b
Results count: 1, includes count: 1
Request #  13: POST    -     0 ms - 759e59c1-af04-4ba1-9dc7-66b960d9fe99 - 200 - http://localhost:8083/databases/759e59c1-af04-4ba1-9dc7-66b960d9fe99/transaction/prepare?tx=08464196-4f53-4e64-8738-6a060ca7acc5:2
Request #  14: POST    -     0 ms - 759e59c1-af04-4ba1-9dc7-66b960d9fe99 - 200 - http://localhost:8083/databases/759e59c1-af04-4ba1-9dc7-66b960d9fe99/transaction/commit?tx=08464196-4f53-4e64-8738-6a060ca7acc5:2
```
everything in the correct order.

@danielmarbach we may need you async guru skills here :wink:

**Comment by danielmarbach** [comment]
@johnsimons

Did you use NSB v5? Because NSB v5 has concurrency set to 1 by default.

**Comment by johnsimons** [comment]
@danielmarbach I did modify the test in v5 and upped the concurrency, :wink:

**Comment by danielmarbach** [comment]
Can you attach the samples so that I can use it?

**Comment by johnsimons** [comment]
@danielmarbach its not a sample, is just the Acceptance tests, ping me and i can show u

**Comment by DavidBoike** [comment]
Added the etag in #155. Now this is just an investigative branch to try to figure out what's going on with Raven's async API.

**Comment by colin-higgins** [comment]
Fixed in https://github.com/Particular/NServiceBus.RavenDB/pull/169

**Pull request closed without merging**
