### PR TITLE
Updated to v6 core code

### PR DESCRIPTION
**Pull request by johnsimons**
### Doco updates

- [ ] Stale reads are nolonger supported and the setting to opt-in is obsoleted

### CODE REVIEW

**Comment by SimonCropp** [comment]
@danielmarbach i fixed a few issues (eg nuget range, missing tostring) but some things i dont know how to handle

 * handling multiple unique/correlation properties  https://github.com/Particular/NServiceBus.RavenDB/issues/64
 * some tests are failing with "Raven.Abstractions.Exceptions.ConcurrencyException : Transaction operation attempted using a non current etag" is this something related to your async PR to ravendb?

**Comment by danielmarbach** [comment]
I pulled in the latest ATT fixes from the core and the batching stuff. It seems the batching stuff kills the `OpenSessionBehavior` in the case of the outbox. We are no longer able to float the session into the outbox persister.

```
First Level Retry is going to retry message 'de8b3078-e224-4ef5-8e7a-a52500ff8649' because of an exception: System.Collections.Generic.KeyNotFoundException: No item found in behavior context with key: Raven.Client.IDocumentSession
   at NServiceBus.Extensibility.ContextBag.Get[T](String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Extensibility\ContextBag.cs:line 149
   at NServiceBus.RavenDB.Outbox.OutboxStorageOptionsExtensions.GetSession(OutboxStorageOptions options) in C:\particular\NServiceBus.RavenDB\src\NServiceBus.RavenDB\Outbox\OutboxStorageOptionsExtensions.cs:line 10
   at NServiceBus.RavenDB.Outbox.OutboxPersister.Store(OutboxMessage outboxMessage, OutboxStorageOptions options) in C:\particular\NServiceBus.RavenDB\src\NServiceBus.RavenDB\Outbox\OutboxPersister.cs:line 35
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 41
```

**Comment by danielmarbach** [comment]
Without limitting the concurreny we still have the issue that when multiple endpoints send their subscriptions to the publisher Raven will throw a `ConcurrencyException` FLR kicks in and resolves that problem but because we don't allow exceptions to happen the ATT fails. Going to raise an issue how to improve the ATT framework

**Comment by danielmarbach** [comment]
Here a few things which need to be fixed in core

https://github.com/Particular/NServiceBus/pull/2944
https://github.com/Particular/NServiceBus/pull/2945

**Comment by mauroservienti** [comment]
@danielmarbach which is the reason that under the hood is causing the `ConcurrencyException`?

**Comment by mauroservienti** [comment]
Are we storing all the subscriptions in a single subscription document?

**Comment by andreasohlund** [comment]
@danielmarbach I'll handle the session. As we discussed the whole thing relies on the persisters to know where to inject them selfves. This is super brittle and I'm about to replace that with a explict `OutboxTransaction` that will be called by the core in appropriate places

cc @SzymonPobiega

**Comment by danielmarbach** [comment]
@mauroservienti yes. And since V6 has default concurrency 100 multiple subscription requests are processed and try to access the same doc. Booom

**Comment by mauroservienti** [comment]
So why don't we stop saving subscriptions in a single document and start using unique ids and unique properties, or a simple map/reduce index to build the requested projection?

**Comment by danielmarbach** [comment]
@mauroservienti That's a good idea and we need to check how we can do this with document store listeners in a way which doesn't require patches (although customer probably won't have huge subscription stores). 

But the root problem is a different one. The root problem is that by design in NSB we rely on FLR but the way how the ATT framework is design any logged exception will make the test fail when we don't have `AllowExceptions`. I think we need to rethink how we approach ATTs. See https://github.com/Particular/NServiceBus/issues/2947

**Comment by andreasohlund** [comment]
Here's a pull for a explicit API for the outbox TX
https://github.com/Particular/NServiceBus/pull/2949

**Comment by SimonCropp** [comment]
@andreasohlund this currently fails because we now have many acceptance tests with multiple unique properties. how do u want to handle that in ravendb?

**Comment by andreasohlund** [comment]
Raise and issue and make the test explicit? (yes we would have to make it explicit again after each update :(  )

Other ideas?

**Comment by mauroservienti** [comment]
> Other ideas?

fix `NServiceBus.RavenDB` to support multiple unique properties?

**Comment by andreasohlund** [comment]
I'm working on this one as we speak, stay tuned

**Comment by andreasohlund** [comment]
This one is green now, I will merge this into develop so that we start working with smaller pulls from now on

**Pull request merged**
