### PR TITLE
v3.0.9 fails with System.InvalidOperationException : The Raven/DocumentsByEntityName index must exist in order to determine the document ID strategy.

### LINKED ISSUE #229: v3.0.9 fails with System.InvalidOperationException : The Raven/DocumentsByEntityName index must exist in order to determine the document ID strategy.
When attempting to upgrade https://github.com/Particular/ServiceControl/tree/Upgrade_To_Raven_v3 from v3.0.7 to v3.0.9 I get this error:
```
System.AggregateException : Test run failed due to one or more exception
  ----> NServiceBus.AcceptanceTesting.Support.ScenarioException : Endpoint Contexts.ManagementEndpoint failed to initialize
  ----> System.InvalidOperationException : The Raven/DocumentsByEntityName index must exist in order to determine the document ID strategy. This index is created by RavenDB automatically. Please check in Raven Studio to make sure it exists.
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.Run(IList`1 runDescriptors, IList`1 behaviorDescriptors, IList`1 shoulds, Func`2 done, Int32 limitTestParallelismTo, Action`1 reports, Func`2 allowedExceptions) in C:\Projects\ServiceControl\src\ServiceControl.AcceptanceTesting\Support\ScenarioRunner.cs:line 87
   at NServiceBus.AcceptanceTesting.ScenarioWithContext`1.Run(RunSettings settings) in C:\Projects\ServiceControl\src\ServiceControl.AcceptanceTesting\ScenarioWithContext.cs:line 73
   at NServiceBus.AcceptanceTesting.ScenarioWithContext`1.NServiceBus.AcceptanceTesting.Support.IScenarioWithEndpointBehavior<TContext>.Run(Nullable`1 testExecutionTimeout) in C:\Projects\ServiceControl\src\ServiceControl.AcceptanceTesting\ScenarioWithContext.cs:line 112
   at ServiceBus.Management.AcceptanceTests.Audit.When_a_message_sent_from_third_party_endpoint_with_missing_metadata.Null_TimeSent_should_not_be_cast_to_DateTimeMin() in C:\Projects\ServiceControl\src\ServiceControl.AcceptanceTests\Audit\When_a_message_sent_from_third_party_endpoint_with_missing_metadata.cs:line 26
--ScenarioException
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.InitializeRunners(RunDescriptor runDescriptor, IList`1 behaviorDescriptors) in C:\Projects\ServiceControl\src\ServiceControl.AcceptanceTesting\Support\ScenarioRunner.cs:line 348
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.PerformTestRun(IList`1 behaviorDescriptors, IList`1 shoulds, RunDescriptor runDescriptor, Func`2 done, Func`2 allowedExceptions) in C:\Projects\ServiceControl\src\ServiceControl.AcceptanceTesting\Support\ScenarioRunner.cs:line 159
--InvalidOperationException
   at NServiceBus.RavenDB.Internal.DocumentIdConventions.GetTerms() in C:\Build\src\NServiceBus.RavenDB\Internal\DocumentIdConventions.cs:line 102
   at NServiceBus.RavenDB.Internal.DocumentIdConventions.MapTypeToCollectionName(Type type, CollectionData collectionData) in C:\Build\src\NServiceBus.RavenDB\Internal\DocumentIdConventions.cs:line 130
   at NServiceBus.RavenDB.Internal.DocumentIdConventions.Initialize() in C:\Build\src\NServiceBus.RavenDB\Internal\DocumentIdConventions.cs:line 69
   at NServiceBus.RavenDB.Internal.DocumentIdConventions.FindTypeTagName(Type type) in C:\Build\src\NServiceBus.RavenDB\Internal\DocumentIdConventions.cs:line 38
   at Raven.Client.Document.DocumentConvention.GetTypeTagName(Type type) in c:\Builds\RavenDB-Stable-3.0\Raven.Client.Lightweight\Document\DocumentConvention.cs:line 301
   at Raven.Client.Document.InMemoryDocumentSessionOperations.StoreInternal(Object entity, Etag etag, String id, Boolean forceConcurrencyCheck) in c:\Builds\RavenDB-Stable-3.0\Raven.Client.Lightweight\Document\InMemoryDocumentSessionOperations.cs:line 766
   at Raven.Client.Document.InMemoryDocumentSessionOperations.Store(Object entity) in c:\Builds\RavenDB-Stable-3.0\Raven.Client.Lightweight\Document\InMemoryDocumentSessionOperations.cs:line 698
   at NServiceBus.Unicast.Subscriptions.RavenDB.SubscriptionPersister.StoreNewSubscription(IDocumentSession session, String id, MessageType messageType) in C:\Build\src\NServiceBus.RavenDB\Subscriptions\SubscriptionPersister.cs:line 92
   at NServiceBus.Unicast.Subscriptions.RavenDB.SubscriptionPersister.<>c__DisplayClass5_0.<Subscribe>b__1(KeyValuePair`2 id) in C:\Build\src\NServiceBus.RavenDB\Subscriptions\SubscriptionPersister.cs:line 28
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NServiceBus.Unicast.Subscriptions.RavenDB.SubscriptionPersister.Subscribe(Address client, IEnumerable`1 messageTypes) in C:\Build\src\NServiceBus.RavenDB\Subscriptions\SubscriptionPersister.cs:line 27
   at ServiceControl.Infrastructure.SubscribeToOwnEvents.SubscribeForNonBrokers(Address address, IEnumerable`1 eventTypes) in C:\Projects\ServiceControl\src\ServiceControl\Infrastructure\SubscribeToOwnEvents.cs:line 39
   at ServiceControl.Infrastructure.SubscribeToOwnEvents.Run() in C:\Projects\ServiceControl\src\ServiceControl\Infrastructure\SubscribeToOwnEvents.cs:line 25
   at Particular.ServiceControl.Bootstrapper.ConfigureNServiceBus() in C:\Projects\ServiceControl\src\ServiceControl\Bootstrapper.cs:line 117
   at Particular.ServiceControl.Bootstrapper.Start() in C:\Projects\ServiceControl\src\ServiceControl\Bootstrapper.cs:line 162
   at ServiceBus.Management.AcceptanceTests.Contexts.ManagementEndpointSetup.<>c__DisplayClass0_0.<GetConfiguration>b__2() in C:\Projects\ServiceControl\src\ServiceControl.AcceptanceTests\Contexts\ManagementEndpointSetup.cs:line 49
   at NServiceBus.AcceptanceTesting.Support.EndpointRunner.Initialize(RunDescriptor run, EndpointBehavior endpointBehavior, IDictionary`2 routingTable, String endpointName) in C:\Projects\ServiceControl\src\ServiceControl.AcceptanceTesting\Support\EndpointRunner.cs:line 61
```

To repro it, checkout https://github.com/Particular/ServiceControl/tree/Upgrade_To_Raven_v3 and run the ATs, these should work.
Then update NServiceBus.RavenDB package to v3.0.9
The error above should be visible in some tests:
image

### PR DESCRIPTION
**Pull request by johnsimons**
Fixes #229

### CODE REVIEW

**Comment by johnsimons** [comment]
@Particular/ravendb-persistence-maintainers please review.
I have tested it with ServiceControl and it all works as expected.

**Comment by mauroservienti** [comment]
Looks good, waiting for @DavidBoike that owns that part to confirm.
For my curiosity why the logger has been removed? Was is not used?

**Comment by johnsimons** [comment]
> For my curiosity why the logger has been removed? Was is not used?

Yes, it was not used

**Comment by DavidBoike** [comment]
My fear is that by executing the index, we have no idea if it existed before, or if it is up-to-date. It's possible that, if it really didn't exist, it will be created and be empty/stale. We will immediately query it for terms, and it will return none, so we'll make stuff up that may be wrong, and then we have a real problem.

I'm not sure if it's possible to do a terms query with NonStaleResultsAsOfNow?

**Comment by mauroservienti** [comment]
If I get it correctly the `GetTerms` private method is called only once if terms are not defined, this happens at endpoint startup. That specific index is generally superquick even in large databases, do you think is it an option to do a `blocking` query using stats and recursively waiting for the index to be non stale? (I know it is awful)

**Comment by DavidBoike** [comment]
It is awful, but only has to be done when a type is in doubt. So that means on first run, and then any time a new saga type is added.

Especially if we're assuming that 99.9% of the time, the index should already exist and be not-crappy, right? Would a normal ServiceControl instance (that has never had the studio exposed, but is humming along in production) have this index? Is it mostly just the clean-slate test cases that we're having problems with?

**Comment by johnsimons** [comment]
> we have no idea if it existed before, or if it is up-to-date

@DavidBoike the code before was also not checking if the index was up to date or not, so this PR doesn't really change that

**Comment by johnsimons** [comment]
Also, looking at the code, it would be nice to avoid that query completely if Timeouts/Sagas feature are turned off, which is the case in ServiceControl.

**Comment by johnsimons** [comment]
> Would a normal ServiceControl instance (that has never had the studio exposed, but is humming along in production) have this index? 

Nope, because by default we don't expose studio, but as I said in https://github.com/Particular/NServiceBus.RavenDB/pull/233#issuecomment-218605422, we don't use any of those features, so in essence it would be nice if we could control whether NSB needs to do this at all? Maybe a toggle to disable `LegacyConventions` 

> Is it mostly just the clean-slate test cases that we're having problems with?

No, it happens all the time

**Comment by DavidBoike** [comment]
The feature check is a fantastic idea.

**Comment by johnsimons** [comment]
> The feature check is a fantastic idea.

But I am not sure how to do it ?

**Comment by DavidBoike** [comment]
I am. Will do tomorrow. Thanks for the inspiration!

**Comment by DavidBoike** [comment]
Closing, working on alternate solution for ServiceControl as mentioned in https://github.com/Particular/NServiceBus.RavenDB/pull/235#issuecomment-218923674 (Option 2).

**Pull request closed without merging**
