### PR TITLE
Flag custom session as ours to manage

### PR DESCRIPTION
**Pull request by colin-higgins**
Fixes https://github.com/Particular/NServiceBus.RavenDB/issues/71

This was a simple one line change but I wonder if we should remove the `SessionOwnership` class if we're just going to "own" every session in that context.

Thoughts?

I'm fine with commenting and keeping as is, we can always modify the code internally later on. No breaking changes.

@Particular/ravendb-persistence-maintainers

### CODE REVIEW

**Comment by colin-higgins** [comment]
Re-running build... more quantum bugs...

**Comment by DavidBoike** [comment]
So NH has no concept of SessionOwnership? Right now it looks like the only type of SessionOwnership is an owned SessionOwnership in which case it's just an extra class to GC.

**Comment by colin-higgins** [comment]
NH doesn't have the concept of user configured session, so it was a non-issue. But yeah, I'll remove it.

**Comment by mauroservienti** [comment]
Is the [`ownsSession`](https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateNativeTransactionSynchronizedStorageSession.cs#L13) thing something comparable to a user provided session, even if I think it is not exposed to end user.

@SzymonPobiega should know.

**Comment by colin-higgins** [comment]
@mauroservienti The `ownsSession` flag basically determines whether we commit and dispose the session. My initial thought was that it should be up to the user to do so, but because the user is basically configuring a session factory for us to call, there is no way for them to access it.

**Comment by SzymonPobiega** [comment]
I am a bit late to the game but I agree:)

**Pull request merged**
