### PR TITLE
V6 async

### PR DESCRIPTION
**Pull request by danielmarbach**
Connects to #113

I separated the async API RavenDB API usage from the v6 update path until 

https://github.com/ravendb/ravendb/pull/606

is discussed

### CODE REVIEW

**Comment by SimonCropp** [comment]
@danielmarbach looks like it needs a rebase.

also can this be closed? https://github.com/Particular/NServiceBus.RavenDB/pull/67

**Comment by danielmarbach** [comment]
This is just a backup of the unfinished async work. The idea is to pull in
#67 first and then decide about this one later

-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by SimonCropp** [comment]
ahh ok. i misunderstood

**Comment by danielmarbach** [comment]
@andreasohlund do you still need this one?

**Comment by andreasohlund** [comment]
I'll delete it once done

**Pull request closed without merging**
