### PR TITLE
[WIP] Updating to 6.1.0

### PR DESCRIPTION
**Pull request by andreasohlund**
WIP until the stable 6.1 is out https://github.com/Particular/NServiceBus/pull/4377

### CODE REVIEW

**Comment by DavidBoike** [comment]
This is the result in the build log:

```
[22:12:34][restore] Added package 'NServiceBus.AcceptanceTesting.6.1.0-rc0001' to folder 'C:\BuildAgent\work\c4d62ce02b983878\src\packages'
[22:12:34][restore] WARNING: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
```

???

**Comment by andreasohlund** [comment]
Pretty sure its the `-rc1` part the causes it to go over the limit. All tests where green locally, I propose we wait until I can update to the stable 6.1.0?

**Comment by timbussmann** [comment]
@Particular/ravendb-persistence-maintainers 6.1 is now officially released. Feel free to pick up this PR and update it to the final 6.1 package. It's up to you whether you decide to only update the test projects or if you update the main projects build dependency to 6.1 too. In case of the second option, please be careful to update nuspec dependencies only if you make use of newly available 6.1 APIs.

**Comment by SimonCropp** [comment]
@Particular/ravendb-persistence-maintainers thoughts on this one?

**Comment by DavidBoike** [comment]
Updated code and test sources to 6.1.2, no other changes, no issues with the tests. Leaving nuspec alone, and merging to develop.

**Pull request merged**
