### PR TITLE
 Update NServiceBus core to latest beta

### PR DESCRIPTION
**Pull request by mauroservienti**
Brings RavenDB package ready for next Core beta release cycle

### CODE REVIEW

**Comment by mauroservienti** [comment]
There are many other Nuget packages that are outdated should we update them as well?

**Comment by DavidBoike** [comment]
Wasn't aware this was required for the next beta - I thought we were good to go.

Let's discuss tomorrow?

**Comment by mauroservienti** [comment]
I was under the impression that it was, but I might be completely wrong 😄

**Comment by mauroservienti** [comment]
Now I get what you mean, this is not needed, because we're using * in package references, thus should be enough to run a new build. Closing.

**Pull request closed without merging**
