### PR TITLE
SyncOMatic update

### PR DESCRIPTION
**Pull request by particularbot**

### CODE REVIEW

**Comment by DavidBoike** [comment]
Well this seemed like a giant waste of time.

@Particular/ravendb-persistence-maintainers Are we OK with this change? It makes it harder to look at the code and know what namespaces are involved without having Intellisense.

**Comment by mauroservienti** [comment]
What is the point of making namespaces as short as possible?
I don't like this change, where does it come from?

**Comment by DavidBoike** [comment]
As far as I can tell, it comes from https://github.com/Particular/RepoStandards/commit/7ded4dc24320c29e24923c4b242344a92fb59ae1

**Comment by DavidBoike** [comment]
I don't much like it either.

I pushed a commit that reverts all the changes to the usings, plus another commit that reverts the DotSettings change from https://github.com/Particular/RepoStandards/commit/7ded4dc24320c29e24923c4b242344a92fb59ae1. If we prefer not to change all the using statements we can squash this down and have taken in *most* of RepoStandards. I could leave the namespace changes around on another branch to save us time if we decide we do want to pull it in.

**Comment by mauroservienti** [comment]
Agree.

**Comment by DavidBoike** [comment]
Shortened usings now moved aside to https://github.com/Particular/NServiceBus.RavenDB/commit/7968091de0a349bd30c4a4adf06d6eb62f9f47da.

**Pull request merged**
