### PR TITLE
[WIP] Removing concurrency limit to repro the hanging subscriptions

### PR DESCRIPTION
**Pull request by andreasohlund**

### CODE REVIEW

**Comment by andreasohlund** [comment]
I've narrowed it down to session.Load hanging when running cuncurrently on the buildserver

http://builds.particular.net/viewLog.html?buildTypeId=NServiceBusRavenDB_2AcceptanceTests&buildId=130980

Here the offending code:

https://github.com/Particular/NServiceBus.RavenDB/blob/sub-storage-deadlock/src/NServiceBus.RavenDB/Subscriptions/SubscriptionPersister.cs#L112

I've tried to:

* Suppress the tx scope
* Turn off isolated recovery storage

Ideas?

**Comment by andreasohlund** [comment]
@Particular/tf-async-persistence what should we do with this one? (I'm out of ideas)

**Comment by DavidBoike** [comment]
Confused / lack of context.

**Comment by andreasohlund** [comment]
If you run the test (see changed files) with concurrency > 1 the subscription storage seems to hang on await session.SaveChanges()

**Comment by andreasohlund** [comment]
This only happens on the build server btw

**Comment by mauroservienti** [comment]
@andreasohlund @colin-higgins @DavidBoike is this still an issue?

**Comment by andreasohlund** [comment]
We would need to rebase and see if it fails in TC to know

**Comment by weralabaj** [comment]
Seems like this issue is no longer relevant. Closing.

**Pull request closed without merging**
