### PR TITLE
Check for testable storage session as well

### PR DESCRIPTION
**Pull request by DavidBoike**
Connects to #250 

Opening PR at the end of the day, so I'm pretty sure will pass but no promises.

@Particular/ravendb-persistence-maintainers please review.

### CODE REVIEW

**Comment by DavidBoike** [comment]
Added 2 tests to verify the extension method works in both cases, and rebased. I'll merge when green.

And on my tombstone it shall say: *@mauroservienti made me write the if statement*.

**Comment by mauroservienti** [comment]
@DavidBoike why this went into `release-4` and not into `develop`?

**Comment by DavidBoike** [comment]
Thought develop was essentially dead until NSB.Raven V4 is released.

**Comment by mauroservienti** [comment]
got it. thanks

**Pull request merged**
