### PR TITLE
Expose raven session as an extension method for SynchronizedStorageSession

### LINKED ISSUE #151: IFindSaga needs to get access to IAsyncDocumentSession
It seems we are exposing `IAsyncDocumentSession` as an extension method at the handler context level but we are not doing the same for `IFindSaga`.

Here is how the old code works currently:
```c#
class PaymentTransactionCompletedSagaFinder : IFindSagas<OrderSagaData>.Using<PaymentTransactionCompleted>
{
    ISessionProvider sessionProvider;

    public PaymentTransactionCompletedSagaFinder(ISessionProvider sessionProvider)
    {
        this.sessionProvider = sessionProvider;
    }

    public Task<OrderSagaData> FindBy(PaymentTransactionCompleted message, SynchronizedStorageSession storageSession, ReadOnlyContextBag context)
    {
        IDocumentSession session = sessionProvider.Session;
        return session.LoadByUniqueConstraint<OrderSagaData>(d => d.PaymentTransactionId, message.PaymentTransactionId);
    }
}
```

Also, quite possible related, should we also expose the `IAsyncDocumentSession` for mutators ?

### PR DESCRIPTION
**Pull request by johnsimons**
This has the added benefit of exposing the saga in IFindSaga and is also the way NHibernate does it.

Fixes #151

### CODE REVIEW

**Comment by johnsimons** [comment]
@colin-higgins here it is

**Comment by SzymonPobiega** [comment]
Yeah, storage session is the way to go.

**Comment by colin-higgins** [comment]
This will need to take into account the user configuring a shared session.

**Comment by johnsimons** [comment]
Not following @colin-higgins ? Can u expand on that ?
How does a use configure a shared session?

**Comment by colin-higgins** [comment]
@johnsimons 
```
config.UsePersistence<RavenDBPersistence>()
          .UseSharedAsyncSession(() => someSession);
```
There is a test failing in this PR that asserts the shared session is used in the handlers if it is configured.

**Comment by johnsimons** [comment]
ok will have a look at it and fix it

**Pull request merged**
