### PR TITLE
Move ConnectionParameters to NServiceBus namespace

### PR DESCRIPTION
**Pull request by MarcinHoppe**
Connects to Particular/PlatformDevelopment#733

### CODE REVIEW

**Comment by DavidBoike** [comment]
@MarcinHoppe because it's used by the API that's already in the NServiceBus root NS? That would make sense to me.

@colin-higgins what was your rationale for not moving it originally?

Do we have worries of other libraries providing a similarly named class in the root NS?

**Comment by MarcinHoppe** [comment]
@DavidBoike This change was triggered by this [issue](https://github.com/Particular/docs.particular.net/issues/1474).

**Comment by MarcinHoppe** [comment]
Build and acceptance tests green.

**Comment by colin-higgins** [comment]
My thought was that developers would typically use the app setting.

**Comment by DavidBoike** [comment]
Chatted with @mauroservienti quick to get his opinion. ConnectionParameters itself does not need to be discoverable by the user, because they don't need to find ConnectionParameters and then figure out what to do with it. They will find the method in the NSB namespace and then the IDE will fill in the using for them on the parameter. So my thought is to close this and leave it where it is.

Side note: The PR where we reorganized namespaces didn't include things we did before under the guise of "Major version we can break stuff" so there are a few more namespaces that have changed.

**Comment by MarcinHoppe** [comment]
@DavidBoike Good point regarding discoverability.

**Comment by DavidBoike** [comment]
@MarcinHoppe It was Mauro's ;-)

**Pull request closed without merging**
