### PR TITLE
Update to official GitVersion latest, ignore tricky commit messages by SHA

### LINKED ISSUE #277: Update GitVersion, remove custom version
I had [hacked a version of GitVersion](https://github.com/Particular/NServiceBus.RavenDB/commit/dbe15a2490829786a77164b47fd532d36a18a762) that removed the MergeMessageBaseVersionStrategy as a method of determining version, causing a commit message regarding merging Core V6 as an instruction to bump the version to 6.0.

GitVersion now has a new way to deal with this - can't remember the details. We need to upgrade GitVersion and then fix the build using that method.

### PR DESCRIPTION
**Pull request by DavidBoike**
Fixes #277

### CODE REVIEW

**Comment by DavidBoike** [comment]
@Particular/ravendb-persistence-maintainers please have a look when you're back.

**Comment by mauroservienti** [comment]
Just one question: what are the commits we're ignoring?

**Comment by DavidBoike** [comment]
The first two I threw in after looking through the git log:

> Upgrade nuget packages to v6.0.0-unstable1328

> Upgrade to v6.0.0-unstable1293
>    
>    Remove unnecessary mocks

After I did that and the build still didn't work, I had to closely inspect the build log to find this commit, which definitely was a fail, because of the merge from a poorly named branch.

> Merge pull request #127 from Particular/upgrade-v6.0.0-unstable1293
>
> Upgrade v6.0.0 unstable1293

After your comment @mauroservienti I got curious and tried removing the first 2 SHAs and the build still worked locally, so I removed the first 2 that are apparently OK.

**Lesson: No versions in branch names please!**

Since I had your approval before, if TC succeeds I'll merge.

**Comment by mauroservienti** [comment]
GitVersion magic :wink:

**Pull request merged**
