### PR TITLE
Remove unused IAsyncSessionProvider

### PR DESCRIPTION
**Pull request by colin-higgins**
@Particular/tf-async-persistence 

Removing an unused session provider with bad constructor arguments

### CODE REVIEW

**Comment by mauroservienti** [comment]
@colin-higgins @DavidBoike sorry to be late at the party, but I think [we messed up something here](https://github.com/Particular/docs.particular.net/pull/1121).

An `IAsyncSessionProvider` instance should be registered per message context as it may be required by some advanced scenarios. Removing it is breaking the actual behavior.

We have the `RavenAsyncSessionFactory` but is not used anywhere.

Am I on the right track or am I missing something obvious?

**Comment by johnsimons** [comment]
IMHO, I would like to see the session exposed via the context and not via DI

**Comment by mauroservienti** [comment]
@johnsimons it is, my bad. @colin-higgins will take care of updating you with all the details, tomorrow I'll be on a flight to UK.

**Comment by colin-higgins** [comment]
@johnsimons The session IS exposed via `messageHandlerContext.GetRavenSession()`

@kbaley has been working on the samples and we had a long outstanding PR for that change.

**Comment by johnsimons** [comment]
Cool @colin-higgins, in that case we need to update the obsolete messages

**Comment by johnsimons** [comment]
Actually there is one thing missing, we need an extension method for `IFindSagas<OrderSagaData>.Using<PaymentTransactionCompleted>.FindBy`

**Comment by johnsimons** [comment]
@colin-higgins it seems the `IAsyncSessionProvider` and the impl is still present in the code, is this suppose to exist ?

**Comment by colin-higgins** [comment]
@johnsimons @mauroservienti Do we need to update the obsoletes? I thought that `IAsyncSessionProvider` was introduced with v6?

**Comment by mauroservienti** [comment]
Introduced in V6 yes as a replacement of `ISessionProvider`

**Pull request merged**
