### PR TITLE
[WIP] API improvements

### PR DESCRIPTION
**Pull request by weralabaj**
Resolves https://github.com/Particular/NServiceBus.RavenDB/issues/262.

@Particular/ravendb-persistence-maintainers shall we do it?

### CODE REVIEW

**Comment by SimonCropp** [comment]
So are either of these Apis tested?

**Comment by DavidBoike** [comment]
@SimonCropp What kind of tests would you see being useful?

Yeah, it doesn't make much sense for those methods to hang off of EndpointConfiguration. In my mind I thought they extended PersistenceExtensions but clearly they don't.

Would the intent be for NHibernate to have the same extension methods just by agreement? And what would then happen if both Raven and NH were included in the same AppDomain? It would just come down to using statements?

**Comment by mauroservienti** [comment]
Was the previous API tested?
I'd say that from the testing perspective we should be good to go with testing that the setting is set with the expected value and that's it.

> Would the intent be for NHibernate to have the same extension methods just by agreement?

I was wondering the same thing, given that Outbox is a Core feature and given that these 2 specific settings don't depend on the storage type shouldn't they be exposed by Core?

> And what would then happen if both Raven and NH were included in the same AppDomain? It would just come down to using statements?

An extension-methods-nightmare :joy:

**Comment by weralabaj** [comment]
> shouldn't they be exposed by Core

Do all persistences support outbox?

**Comment by mauroservienti** [comment]
I don't know, but I expect the call to `EnableOutbox` to throw if the persistence of choice doesn't support the outbox.

**Comment by weralabaj** [comment]
I'm not sure if we can make those changes in core, maintainers don't want any changes now that are not very critical, and that one doesn't seem to be. So IMO either we do it here or not at all before next minor of v6.

**Comment by mauroservienti** [comment]
We can make them here now, or in a minor version, and move to core in V7. I'd prefer now versus in a minor version to avoid the "obsoletion" steps

**Comment by weralabaj** [comment]
@mauroservienti see https://github.com/Particular/NServiceBus/issues/4071

**Comment by DavidBoike** [comment]
I added tests, and also put the old API back in with ObsoleteEx markers.

Ultimately we probably should not do this unless NHibernate is going to do the same.

@Particular/nhibernate-persistence-maintainers, are you planning to move this API for RC as well?

**Comment by mauroservienti** [comment]
@DavidBoike Are we only waiting for NH to be aligned?

**Comment by DavidBoike** [comment]
Because of difficulties in API coordination between the Core and NHibernate, there's no good way to structure this API given that we're so close to RC. We'll have to live with it for now.

**Pull request closed without merging**
