### PR TITLE
remove raven client  server checks

### PR DESCRIPTION
**Pull request by SimonCropp**
we are overstepping the bounds of our problem domain. It is not our job to dictate the compat between raven client and server. if people think this code should exist then please send a PR to the RavenDB  codebase.

### CODE REVIEW

**Comment by andreasohlund** [comment]
I agree in general but I think there is a grey zone where we have our own requirements? ( @johnsimons wasn't there a time where we needed a specific version or higher due to some DTC bug? )

**Comment by johnsimons** [comment]
@andreasohlund yes, we had to ensure the server was running a specific patched version or higher otherwise the DTC was broken.
In principal I also agree with @SimonCropp proposal but since this has bitten us before and we had raven as the default persistence, I do think is our duty to ensure that things are going to work correctly.

**Comment by SimonCropp** [comment]
@johnsimons i think the amount of bugs we have had with our version check code negates any value we deliver. and it is not our responsibility to monkey patch client server relationships. we dont check the version of sql we talk to and force them to update to a latest patch version

**Comment by andreasohlund** [comment]
>proposal but since this has bitten us before and we had raven as the default persistence, I do think is our duty to ensure that things are going to work correctly.

Since raven isn't the default any more and we don't do any server checks on sqlserver I'm with @SimonCropp => lets remove it

**Comment by johnsimons** [comment]
I also agree that removing this dodgy code is a good thing.

**Pull request merged**
